[package]
name = "which"
version = "1.0.3"
authors = ["fangyuanziti <tiziyuanfang@gmail.com>"]
repository = "https://github.com/fangyuanziti/which-rs.git"
documentation = "https://docs.rs/which/"
license = "MIT"
description= "A Rust equivalent of Unix command \"which\". Locate installed execuable in cross platforms."
readme= "README.md"
categories = ["os", "filesystem"]
keywords = ["which", "which-rs", "unix", "command"]

[dependencies]
libc = "0.2.10"

[dev-dependencies]
failure = "0.1.1"
tempdir = "0.3.4"
